// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-trips.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated" }],
    isError: true
  };
}
function errorResult(message) {
  return {
    content: [{ type: "text", text: message }],
    isError: true
  };
}

// src/lib/mcp/tools/list-trips.ts
var list_trips_default = defineTool({
  name: "list_trips",
  title: "List trips",
  description: "List the signed-in user's trips (id, name, destination, dates, status, budget).",
  inputSchema: {
    status: z.string().optional().describe("Optional trip status filter, e.g. 'Planning \u{1F4DD}'"),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("trips").select("id,name,destination,start_date,end_date,base_currency,status,budget").order("start_date", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { trips: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-trip.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_trip_default = defineTool2({
  name: "get_trip",
  title: "Get trip",
  description: "Fetch a single trip with all its events (itinerary).",
  inputSchema: {
    trip_id: z2.string().uuid().describe("The trip's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ trip_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data: trip, error: tErr } = await sb.from("trips").select("*").eq("id", trip_id).maybeSingle();
    if (tErr) return errorResult(tErr.message);
    if (!trip) return errorResult("Trip not found or access denied.");
    const { data: events, error: eErr } = await sb.from("events").select("*").eq("trip_id", trip_id).order("sort_order", { ascending: true });
    if (eErr) return errorResult(eErr.message);
    const payload = { trip, events: events ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-trip.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
var create_trip_default = defineTool3({
  name: "create_trip",
  title: "Create trip",
  description: "Create a new trip for the signed-in user.",
  inputSchema: {
    name: z3.string().min(1).describe("Trip name."),
    destination: z3.string().optional(),
    start_date: z3.string().describe("ISO date, e.g. 2026-05-10"),
    end_date: z3.string().describe("ISO date, e.g. 2026-05-14"),
    base_currency: z3.string().optional().describe("ISO currency, default USD"),
    status: z3.string().optional().describe("Trip status, e.g. 'Planning \u{1F4DD}'"),
    budget: z3.number().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("trips").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      destination: input.destination,
      start_date: input.start_date,
      end_date: input.end_date,
      base_currency: input.base_currency ?? "USD",
      status: input.status ?? "Planning \u{1F4DD}",
      budget: input.budget
    }).select().single();
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: `Created trip ${data.id}` }],
      structuredContent: { trip: data }
    };
  }
});

// src/lib/mcp/tools/add-event.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
var add_event_default = defineTool4({
  name: "add_event",
  title: "Add event to trip",
  description: "Add an itinerary event (flight, hotel, activity, food, etc.) to a trip.",
  inputSchema: {
    trip_id: z4.string().uuid(),
    date: z4.string().describe("ISO date."),
    time: z4.string().optional().describe("HH:MM"),
    end_time: z4.string().optional(),
    category: z4.string().describe("e.g. 'Activity \u{1F3AD}', 'Food \u{1F37D}\uFE0F', 'Flights \u2708\uFE0F'"),
    title: z4.string().min(1),
    amount: z4.number().optional(),
    currency: z4.string().optional(),
    payment_method: z4.string().optional().describe("Credit | Debit | Cash | Other"),
    notes: z4.string().optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("events").insert({
      trip_id: input.trip_id,
      user_id: ctx.getUserId(),
      date: input.date,
      time: input.time ?? "09:00",
      end_time: input.end_time,
      category: input.category,
      title: input.title,
      amount: input.amount ?? 0,
      currency: input.currency ?? "USD",
      payment_method: input.payment_method ?? "Credit",
      details: {},
      notes: input.notes
    }).select().single();
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: `Added event ${data.id}` }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/tools/list-checklist.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^4.4.3";
var list_checklist_default = defineTool5({
  name: "list_checklist",
  title: "List trip checklist",
  description: "List checklist items for a trip.",
  inputSchema: {
    trip_id: z5.string().uuid(),
    only_open: z5.boolean().optional().describe("If true, return only incomplete items.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ trip_id, only_open }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("checklist_items").select("id,text,category,priority,is_completed,due_date,assignee,sort_order").eq("trip_id", trip_id).order("sort_order", { ascending: true });
    if (only_open) q = q.eq("is_completed", false);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lvzfgjqepuvuezoxmsdk";
var mcp_default = defineMcp({
  name: "wonderjourney-mcp",
  title: "WonderJourney",
  version: "0.1.0",
  instructions: "Tools for WonderJourney \u2014 a trip planner. Use `list_trips` to see the user's trips, `get_trip` for a trip's full itinerary and events, `create_trip` to start a new trip, `add_event` to add itinerary items, and `list_checklist` for packing/todo items. All tools act as the signed-in user; trips and events respect row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_trips_default, get_trip_default, create_trip_default, add_event_default, list_checklist_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
